DET_SOURCE_DIR: '/home/yuqiang/yl4300/project/MCVT_YQ/datasets/algorithm_results/detection/images/test/S06/'
REID_MODEL: 'reid_model/resnext101_ibn_a_2.pth'
REID_BACKBONE: 'resnext101_ibn_a'
DET_IMG_DIR: '/home/yuqiang/yl4300/project/MCVT_YQ/datasets/algorithm_results/detect_merge/'
DATA_DIR: '/home/yuqiang/yl4300/project/MCVT_YQ/datasets/algorithm_results/detect_reid2/'
REID_SIZE_TEST: [384, 384]
