DET_SOURCE_DIR: '/home/yuqiang/yl4300/project/MCVT_YQ/datasets/algorithm_results_train/detection/images/train/S01/'
REID_MODEL: 'reid_model/resnet101_ibn_a_3.pth'
REID_BACKBONE: 'resnet101_ibn_a'
DET_IMG_DIR: '/home/yuqiang/yl4300/project/MCVT_YQ/datasets/algorithm_results_train/detect_merge/'
DATA_DIR: '/home/yuqiang/yl4300/project/MCVT_YQ/datasets/algorithm_results_train/detect_reid3/'
REID_SIZE_TEST: [384, 384]
