CHALLENGE_DATA_DIR: '/home/yuqiang/yl4300/project/MCVT_YQ/datasets/AIC22_Track1_MTMC_Tracking/'
DET_SOURCE_DIR: '/home/yuqiang/yl4300/project/MCVT_YQ/datasets/algorithm_results_train/detection/images/train/S01/'
DATA_DIR: '/home/yuqiang/yl4300/project/MCVT_YQ/datasets/algorithm_results_train/detect_merge/'
REID_SIZE_TEST: [384, 384]    # 384, 256
ROI_DIR: '/home/yuqiang/yl4300/project/MCVT_YQ/datasets/AIC22_Track1_MTMC_Tracking/train/S01/'
CID_BIAS_DIR: '/home/yuqiang/yl4300/project/MCVT_YQ/datasets/AIC22_Track1_MTMC_Tracking/cam_timestamp/'
USE_RERANK: True
USE_FF: True
SCORE_THR: 0.1
MCMT_OUTPUT_TXT: 'track1.txt'